name:                Advent2017
version:             0.1.0.0
github:              "Neongraal/Advent"
license:             BSD3
author:              "NeonGraal"
maintainer:          "github@scifi.geek.nz"
copyright:           "2022 NeonGraal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/neongraal/Advent#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Advent2017-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Advent2017

tests:
  Advent2017-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Advent2017
    - hspec
